
const PASS='priskin2026';let products=[];const login=document.getElementById('login'),dashboard=document.getElementById('dashboard'),list=document.getElementById('adminList');
if(sessionStorage.getItem('priskinAdminV3')==='yes')openDash();
loginBtn.onclick=()=>{if(password.value===PASS){sessionStorage.setItem('priskinAdminV3','yes');openDash()}else alert('Contraseña incorrecta')};logoutBtn.onclick=()=>{sessionStorage.removeItem('priskinAdminV3');location.reload()};
async function openDash(){login.classList.add('hidden');dashboard.classList.remove('hidden');const saved=localStorage.getItem('priskinProductsV3');products=saved?JSON.parse(saved):await(await fetch('products.json')).json();render()}
function save(){localStorage.setItem('priskinProductsV3',JSON.stringify(products))}
function render(){list.innerHTML=products.map(p=>`<article class="row ${p.available===false?'unavailable':''}"><img src="${p.image}"><div><h3>${esc(p.name)}</h3><p>${esc(p.brand)} · ${esc(p.category)} · ${esc(p.price)}</p></div><div class="row-actions"><button onclick="edit(${p.id})">Editar</button><button class="light" onclick="toggle(${p.id})">${p.available===false?'Activar':'Ocultar'}</button><button class="light" onclick="removeP(${p.id})">Eliminar</button></div></article>`).join('')}
function edit(id){const p=products.find(x=>x.id===id);productId.value=p.id;name.value=p.name;brand.value=p.brand;category.value=p.category;price.value=p.price;description.value=p.description;scrollTo({top:0,behavior:'smooth'})}
saveBtn.onclick=()=>{const id=productId.value?Number(productId.value):Date.now();const existing=products.find(p=>p.id===id);const finish=img=>{const data={id,name:name.value||'Nuevo producto',brand:brand.value||'Marca',category:category.value||'Categoría',price:price.value||'₡ 0 000',description:description.value||'',image:img||(existing?existing.image:'images/01-mixsoon-bean-sun-stick.jpg'),available:existing?existing.available:true,featured:existing?existing.featured:false};existing?Object.assign(existing,data):products.push(data);save();clear();render();alert('Producto guardado')};const file=image.files[0];if(file){const r=new FileReader();r.onload=e=>finish(e.target.result);r.readAsDataURL(file)}else finish(null)}
newBtn.onclick=clear;cancelBtn.onclick=clear;function clear(){productId.value='';name.value='';brand.value='';category.value='';price.value='';description.value='';image.value=''}
function toggle(id){const p=products.find(x=>x.id===id);p.available=p.available===false?true:false;save();render()}
function removeP(id){if(confirm('¿Eliminar producto?')){products=products.filter(p=>p.id!==id);save();render()}}
exportBtn.onclick=()=>{const blob=new Blob([JSON.stringify(products,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='products.json';a.click()}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
