
let products=[];
const grid=document.getElementById('productGrid'),search=document.getElementById('search'),brandSelect=document.getElementById('brandSelect'),catSelect=document.getElementById('catSelect'),countText=document.getElementById('countText'),brandButtons=document.getElementById('brandButtons');
async function init(){const saved=localStorage.getItem('priskinProductsV3');products=saved?JSON.parse(saved):await(await fetch('products.json')).json();setup();render()}
function setup(){const brands=[...new Set(products.map(p=>p.brand))].sort();brands.forEach(b=>{brandSelect.innerHTML+=`<option>${esc(b)}</option>`;brandButtons.innerHTML+=`<button class="brand-pill" onclick="chooseBrand('${safeAttr(b)}')">${esc(b)}</button>`});[...new Set(products.map(p=>p.category))].sort().forEach(c=>catSelect.innerHTML+=`<option>${esc(c)}</option>`)}
function chooseBrand(b){brandSelect.value=b;document.getElementById('catalogo').scrollIntoView({behavior:'smooth'});render()}
function render(){const q=search.value.toLowerCase(),b=brandSelect.value,c=catSelect.value;const list=products.filter(p=>p.available!==false).filter(p=>(!b||p.brand===b)&&(!c||p.category===c)&&(!q||`${p.name} ${p.brand} ${p.category} ${p.description}`.toLowerCase().includes(q)));countText.textContent=`${list.length} productos disponibles`;grid.innerHTML=list.map(card).join('');if(list[0])heroImg.src=list[0].image}
function card(p){const msg=encodeURIComponent(`Hola PriSkin, quiero información de: ${p.name} - ${p.price} XMAYOR`);return `<article class="card"><div class="pic"><img src="${p.image}" alt="${esc(p.name)}"></div><div class="body"><div class="brand">${esc(p.brand)} · ${esc(p.category)}</div><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="price"><strong>${esc(p.price)}</strong><span>XMAYOR</span></div><a class="wa" target="_blank" href="https://wa.me/50662315954?text=${msg}">Solicitar</a></div></article>`}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function safeAttr(s){return String(s).replace(/'/g,"\\'")}
[search,brandSelect,catSelect].forEach(el=>el.addEventListener('input',render));clearBtn.onclick=()=>{search.value='';brandSelect.value='';catSelect.value='';render()};menuBtn.onclick=()=>navMenu.classList.toggle('open');init();
