
let products=[], filtered=[];
const grid=document.getElementById('productGrid'), search=document.getElementById('search'), brandSelect=document.getElementById('brandSelect'), catSelect=document.getElementById('catSelect'), countText=document.getElementById('countText');
async function init(){const saved=localStorage.getItem('priskinProductsV2'); products=saved?JSON.parse(saved):await (await fetch('products.json')).json(); setupFilters(); render();}
function setupFilters(){[...new Set(products.map(p=>p.brand))].sort().forEach(b=>brandSelect.innerHTML+=`<option>${esc(b)}</option>`);[...new Set(products.map(p=>p.category))].sort().forEach(c=>catSelect.innerHTML+=`<option>${esc(c)}</option>`)}
function render(){const q=search.value.toLowerCase(), b=brandSelect.value, c=catSelect.value; filtered=products.filter(p=>p.available!==false).filter(p=>(!b||p.brand===b)&&(!c||p.category===c)&&(!q||`${p.name} ${p.brand} ${p.category} ${p.description}`.toLowerCase().includes(q)));countText.textContent=`${filtered.length} productos disponibles`;grid.innerHTML=filtered.map(card).join(''); if(filtered[0]) document.getElementById('heroImg').src=filtered[0].image;}
function card(p){return `<article class="card"><div class="pic"><img src="${p.image}" alt="${esc(p.name)}"></div><div class="card-body"><div class="brand">${esc(p.brand)} · ${esc(p.category)}</div><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="price"><strong>${esc(p.price)}</strong><span>XMAYOR</span></div></div></article>`}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
[search,brandSelect,catSelect].forEach(el=>el.addEventListener('input',render));clearBtn.onclick=()=>{search.value='';brandSelect.value='';catSelect.value='';render()};init();
